### ISSUE TITLE
Error in converting Lore rules to GLocalX rules

### ISSUE THREAD

**Issue by 18899599213** [msetzu/glocalx#1]
Hi, I'm a graduated student from China. I followed the requirements in converting Lore rules to GLocalX rules, loaders\lore lines 26-30 extracts many attributions from Lore rules, however ,the Lore rules do not have such attributions, could you please show me a Lore rule example that can be correctly converted into GlocalX rule, thanks a lot! :)

**Comment by msetzu** [comment]
Hi, when developing the algorithm I used a slightly different version of Lore, not synced with the [official repo](https://github.com/riccotti/LORE). If you can share a couple of rules I can update the code

**Comment by 18899599213** [comment]
Hi, I used the official repo to produce Lore rule with german_credit.csv, its format is "[{'default': 1}, {'duration_in_month': '>23'}, [505.0, 15.1]]", pyyadt.py line 225 shows the format of rules, it is "rule = [cons, ant, weights]".

**Comment by msetzu** [comment]
Sorry for the delay, I've updated the code, try [this gist](https://gist.github.com/msetzu/48e6bcdc5f1eb3b48e062d8ffad47af1) and let me know if it works

**Comment by Edris-Hosseini** [comment]
Thanks for sharing and updating [this gist](https://gist.github.com/msetzu/48e6bcdc5f1eb3b48e062d8ffad47af1)

Now compatible with the rule extracted from Lore.
